### ISSUE TITLE
xdmeme is broken

### ISSUE THREAD

**Issue by Flyingkit** [ThzeTerminator/weedbot420issues#6]
**Is this a bug related to a command? If so, which one?**
xdmeme

**Describe the bug**
you already know, the text is fucked. Sometimes it's too small sometimes it's too big. The ratio don't add up. It overlaps and doesn't resize itself. 

**To Reproduce**
Provide step-by-step how to replicate the bug
1. type xdmeme 
2. type long text afterwards or korean letters

**Expected behavior**
the fucking thing to work 

**Screenshots**
Add screenshots to help explain your problem, especially regarding images
sorry

**Additional context**
Add any other context about the problem here if applicable. You can remove this section otherwise
:)

**Comment by ThzeTerminator** [comment]
Issue already exists on my project repo and the meme command is still considered (internally) as in development. Fixing it might take longer then expected due to the difficult nature of automating image editing.

Image template memes (e.g `trump`) and `sonic` are easy to use considering I get to set the width and height of the resulting image. This is not the case when making something such as `meme`.

**Comment by ThzeTerminator** [comment]
![image](https://user-images.githubusercontent.com/33174349/108740475-01929700-7536-11eb-89ad-9f653350ef06.png)
Swapped the methods used to edit images, text now gets wrapped thanks to it.

It's only a matter of getting a good fontsize, which I still need some work on, though it should now be 'normal sized'

**Comment by ThzeTerminator** [comment]
I've reworked how the meme command works due to some oversights that I've not accounted for.

using `{prefix}`meme when the target image **is not** a GIF results it in using the way I indent it to work.

using `{prefix}`meme when the target image **is** a GIF results it in using an alternative way which has some flaws (e.g no font wrap).

I'm closing the issue since it does work properly, however I'm aware of the current issues with the gifs
